### GET person with the phone number 45454545
GET http://localhost:8080/CA1/api/ca1/person/phone/45454545
accept:application/json

### GET all persons that do the hobby 3D-udskrivning
GET http://localhost:8080/CA1/api/ca1/person/hobby/3D-udskrivning
accept:application/json

### GET a list of all zipcodes in denmark
GET http://localhost:8080/CA1/api/ca1/zipcodes
accept:application/json

### GET all persons that live in the city with zipcode 3720
GET http://localhost:8080/CA1/api/ca1/person/city/3720
accept:application/json

### GET a count of all persons doing the hobby 3D-udskrivning
GET http://localhost:8080/CA1/api/ca1/hobby/3D-udskrivning/count
accept:application/json

### POST new person
POST http://localhost:8080/CA1/api/ca1/person
Content-Type: application/json
accept:application/json

{
  "email": "created@one.com",
  "firstName": "Post-man",
  "lastName": "Per",
  "phones": [
    {
      "number": "91011121",
      "description": "arbejdstelefon"
    }
  ],
  "fullAddress": {
    "street": "teststreet",
    "additionalInfo": "th",
    "zipCode": "3720",
    "city": "Aakirkeby"
  },
  "hobbies": [
    {
      "id": 404,
      "name": "Hundesport",
      "wikiLink": "https://en.wikipedia.org/wiki/Dog_sport",
      "category": "Konkurrence",
      "type": "Udendørs"
    }
  ]
}
